<?php
function prettyPrint($a) {
    echo "<pre>";
    // $pretty = json_encode($a, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    print_r($a);
    echo "</pre>";
}
?>
<div class='twoColumn'>
    <div class="width29 float margin">
        <h1>Available Indices</h1>
        <?php
            $indices = $this->indices;
            $keys = array_keys($indices);
            foreach ($keys as $key) {
                echo '<div class="messagebox indexBox">';
                echo '<h4>' . $key . '</h4>';
                echo 'documents: ' . $indices[$key]['docs']['num_docs'];
                echo "<br>";
                echo '<a href=#>reindex</a>';
                echo "<br>";
                echo '<a href=#>delete</a>';
                echo "<br>";
                echo "</div>";
            }
        ?>
    </div>
    <div class="width69 float margin">
        <h1>Create new Index</h1>
        <form method="post" class="simple-input" name="create-index">
            <fieldset>
                <div>
                    <input class="text focusNextOnEnter" id="indexname" name="indexname" value="" type="text">
                    <input id="submit-create-index" type="submit" value="Create Index" class="submit"/>
                    <span id='create-index-response'></span>
                </div>
            </fieldset>
        </form>
        <h1>Index Server Information</h1>
    </div>
</div>
<?php
// echo prettyPrint($this->model->getPredicates())
?>