<?php
function prettyPrint($a) {
    echo "<pre>";
    // $pretty = json_encode($a, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    print_r($a);
    echo "</pre>";
}
function startsWith($haystack, $needle)
{
    $length = strlen($needle);
    return (substr($haystack, 0, $length) === $needle);
}
?>
<!--<div class='twoColumn'>-->
    <div id="indices">
        <h1>Available Indices</h1>
        <p>
            <a href='reindexclass'>full reindex</a>
        </p>
        <?php
            $indices = $this->indices;
            $keys = array_keys($indices);
            foreach ($keys as $key) {

                // hide indices starting with a dot
                if (startsWith($key, ".")) {
                    break;
                }
                echo '<div class="indexBox">';
                echo '<div class="indexname">' . $key . '</div>';
                echo '<div class="count"></div>';
                echo '<div class="indexfooter"></div>';
                echo "</div>";
            }
        ?>
    </div>
<!--    <div class="width69 float margin">-->
<!--        <h1>Create new Index</h1>-->
<!--        <form method="post" class="simple-input" name="create-index">-->
<!--            <fieldset>-->
<!--                <div>-->
<!--                    <input class="text focusNextOnEnter" id="indexname" name="indexname" value="" type="text">-->
<!--                    <input id="submit-create-index" type="submit" value="Create Index" class="submit"/>-->
<!--                    <span id='create-index-response'></span>-->
<!--                </div>-->
<!--            </fieldset>-->
<!--        </form>-->
<!--        <!-- <h1>Index Server Information</h1> -->
<!--    </div>-->
<!--</div>-->
<?php
// echo prettyPrint($this->model->getPredicates())
?>