<?php
function prettyPrint($a) {
      echo "<pre>";
      $pretty = json_encode($a, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
      print_r($pretty);
    echo "</pre>";
}
?>
<h1>Fulltext search results for: <?php echo $this->input ?></h1>
<div id="show-filter"><a id="show-filter-btn" class="minibutton">Show filter</a></div>
<!-- The list of filters -->
<div id="filter-list" style="display: none">
    <?php foreach ($this->availableIndices as $index) :?>
    <?php if((in_array($index, $this->selectedIndices))): ?>
    <div>
        <label class="checkboxradio">
            <input class="checkbox" type="checkbox"  value="<?php echo $index; ?>" checked><?php echo $index; ?>
        </label>
    </div>
    <?php else: ?>
    <div>
        <label class="checkboxradio">
            <input class="checkbox" type="checkbox" value="<?php echo $index; ?>"><?php echo $index; ?>
        </label>
    </div>
    <?php endif; ?>
    <?php endforeach; ?>
    <a id="filter-apply-btn" class="minibutton" href="<?php echo OntoWiki::getInstance()->getUrlBase() ?>fulltextsearch/search?input=<?php echo $this->input ?>">Apply filter</a>
</div>
<br />
<?php $odd = false; ?>
<?php if (!empty($this->resultArray)) { ?>
<table class="separated-vertical" id="history-list">
    <thead>
        <!-- table headers -->
        <tr class="odd">
            <!-- <th><?php echo $this->_('select'); ?>          </th> -->
            <th>ID</th>
            <th>Label</th>
            <th>Highlight (what part has matched)</th>
            <th>Index</th>
        </tr>
    </thead>
    <tbody>
        <!-- table contents -->
        <?php $i = 0; ?>
        <?php foreach ($this->resultArray as $result) :?>
        <tr class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?> ">
            <td><a href="<?php echo OntoWiki::getInstance()->getUrlBase() ?>resource/properties?r=<?php echo $result['id']; ?>"><?php echo $result['id']; ?></a></td>
            <td><?php echo $result['title']; ?></td>
            <td>
                <span class="hint--bottom" data-hint="<?php echo array_keys($result['highlight'])[0] ?>">
                <?php echo array_values(array_values($result['highlight'])[0])[0]; ?>
                </span>
            </td>
            <td><?php echo $result['index']; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php } else { echo "<p>No results found</p><br /><br />";};?>
<div id="show-json-result">[+] Show results as JSON</div>
<div id="json-result" style="display: none">
    <?php echo prettyPrint($this->jsonResult) ?>
</div>
<div id="show-query">[+] Show query</div>
<div id="query" style="display: none">
    <?php echo prettyPrint($this->query) ?>
</div>
<?php  // echo prettyPrint($this->availableIndices) ?>