<?php
function prettyPrint($a) {
      echo "<pre>";
      $pretty = json_encode($a, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
      print_r($pretty);
    echo "</pre>";
}
?>
<h1><?php echo $this->_('Fulltext search results for') ?>: <?php echo $this->input ?></h1>
<?php $odd = false; ?>
<?php if (!empty($this->resultArray)) { ?>
<table class="display" id="index-list">
    <thead>
        <!-- table headers -->
        <tr class="odd">
            <th><?php echo $this->_('Resource') ?></th>
            <th><?php echo $this->_('Highlight') ?></th>
            <th><?php echo $this->_('Knowledgebase') ?></th>
            <th><?php echo $this->_('Class') ?></th>
        </tr>
    </thead>
    <tbody>
        <!-- table contents -->
        <?php $i = 0; ?>
        <?php foreach ($this->resultArray as $result) :?>
        <tr class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?> ">
            <td><a href="<?php echo OntoWiki::getInstance()->getUrlBase() ?>resource/properties?r=<?php echo urlencode($result['id']); ?>"><?php echo $result['id']; ?></a></td>
            <td>
                <span class="hint--bottom" data-hint="<?php echo $this->titleHelper->getTitle(array_keys($result['highlight'])[0]) ?>">
                <?php echo array_values(array_values($result['highlight'])[0])[0]; ?>
                </span>
            </td>
            <td><?php echo $this->titleHelper->getTitle(str_replace("_", "/", $result['index'])); ?></td>
            <td><?php echo $this->titleHelper->getTitle($result['type']); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php } else { echo "<p>No results found</p><br /><br />";};?>
<div id="show-json-result">[+] <?php echo $this->_('Show results as JSON') ?></div>
<div id="json-result" style="display: none">
    <?php echo prettyPrint($this->jsonResult) ?>
</div>
<div id="show-query">[+] <?php echo $this->_('Show query') ?></div>
<div id="query" style="display: none">
    <?php echo prettyPrint($this->query) ?>
</div>
<script type="text/javascript">
    var showAsJson = '<?php echo $this->_("Show results as JSON") ?>';
    var hideResults = '<?php echo $this->_("Hide results") ?>';
    var showQuery = '<?php echo $this->_("Show query") ?>';
    var hideQuery = '<?php echo $this->_("Hide query") ?>';
    var showFilter = '<?php echo $this->_("Show filter") ?>';
    var hideFilter = '<?php echo $this->_("Hide filter") ?>';
    var noResults = '<?php echo $this->_("No results found") ?>';
    var trigger = '<?php echo $this->_("Press enter to trigger an advanced search") ?>';
</script>
