<link href="../extensions/fulltextsearch/templates/fulltextsearch/fulltextsearch.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="../extensions/fulltextsearch/templates/fulltextsearch/typeahead.bundle.js"></script>
<script type="text/javascript" src="../extensions/fulltextsearch/templates/fulltextsearch/search.js"></script>
<script type="text/javascript">
    var noResults = '<?php echo $this->_("No results found") ?>';
    var trigger = '<?php echo $this->_("Press enter to trigger an advanced search") ?>';
</script>
